# Align Codecov with local lcov --remove filters.
ignore:
  - "build/**"
  - "cpm_modules/**"
  - "include/google/protobuf/**"

flag_management:
  default_rules:
    carryforward: true

coverage:
  status:
    project:
      default:
        flags:
          - ci
