// clang-format off
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// generation command line:
//    protoc --plugin=protoc-gen-hpp=/path/to/protoc-gen-hpp
//           --hpp_out :${out_dir}
//           hpp_proto/hpp_options.proto

#pragma once

#include <hpp_proto/pb_serializer.hpp>
#include "hpp_proto/hpp_options.msg.hpp"
#include "google/protobuf/descriptor.pb.hpp"


namespace hpp::proto {

auto pb_meta(const FileOptions &) -> std::tuple<
  hpp::proto::field_meta<1, &FileOptions::non_owning, hpp::proto::field_option::explicit_presence, bool>,
  hpp::proto::field_meta<2, &FileOptions::namespace_prefix, hpp::proto::field_option::explicit_presence>>;

auto pb_meta(const MessageOptions &) -> std::tuple<
  hpp::proto::field_meta<1, &MessageOptions::non_owning, hpp::proto::field_option::explicit_presence, bool>>;

auto pb_meta(const FieldOptions &) -> std::tuple<
  hpp::proto::field_meta<1, &FieldOptions::non_owning, hpp::proto::field_option::explicit_presence, bool>>;

constexpr auto hpp_file_opts() {
  return hpp::proto::extension_meta<::google::protobuf::FileOptions, 60001, hpp::proto::field_option::none, ::hpp::proto::FileOptions, ::hpp::proto::FileOptions>{};
}

constexpr auto hpp_message_opts() {
  return hpp::proto::extension_meta<::google::protobuf::MessageOptions, 60001, hpp::proto::field_option::none, ::hpp::proto::MessageOptions, ::hpp::proto::MessageOptions>{};
}

constexpr auto hpp_field_opts() {
  return hpp::proto::extension_meta<::google::protobuf::FieldOptions, 60001, hpp::proto::field_option::none, ::hpp::proto::FieldOptions, ::hpp::proto::FieldOptions>{};
}

} // namespace hpp::proto
// clang-format on
