// clang-format off
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// generation command line:
//    protoc --plugin=protoc-gen-hpp=/path/to/protoc-gen-hpp
//           --hpp_out :${out_dir}
//           hpp_proto/hpp_options.proto

#pragma once
#include <hpp_proto/file_descriptor_pb.hpp>

#include "google/protobuf/descriptor.desc.hpp"

namespace hpp_proto::file_descriptors::hpp_proto::hpp_options_proto {

using namespace std::literals::string_view_literals;
inline constexpr ::hpp_proto::file_descriptor_pb file_descriptor_{
  "\n\033hpp_proto/hpp_options.proto\022\thpp_proto\032 google/protobuf/descriptor.proto\"f\n\vFileOptions\022\'\n\020namespace_prefix\030\002(\tR\017namespacePrefix\022.\n\024file_descriptor_name\030\003(\tR\022fileDescriptorName:W\n\rhpp_file_opts\030\204F(\v2\026.hpp_proto.FileOptions\022\034.google.protobuf.FileOptionsR\vhppFileOpts"sv
};

inline auto file_descriptor_set(){
  return ::hpp_proto::distinct_file_descriptor_pb_array{
    ::hpp_proto::file_descriptors::google::protobuf::descriptor_proto::file_descriptor_,
    ::hpp_proto::file_descriptors::hpp_proto::hpp_options_proto::file_descriptor_,
  };
}
} // namespace hpp_proto::file_descriptors::hpp_proto::hpp_options_proto

// clang-format on
