// clang-format off
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// generation command line:
//    protoc --plugin=protoc-gen-hpp=/path/to/protoc-gen-hpp
//           --hpp_out :${out_dir}
//           hpp_proto/hpp_options.proto

#pragma once

#include <hpp_proto/field_types.hpp>
#include "google/protobuf/descriptor.msg.hpp"
// @@protoc_insertion_point(includes)


namespace hpp::proto {
//NOLINTBEGIN(performance-enum-size)

template <typename Traits = ::hpp::proto::default_traits>
struct FileOptions {
  using hpp_proto_traits_type = Traits;
  hpp::proto::optional<typename Traits::string_t> namespace_prefix;

  [[no_unique_address]] hpp::proto::pb_unknown_fields<Traits> unknown_fields_;
  bool operator == (const FileOptions&) const = default;
};

template <typename Traits>
constexpr auto message_type_url(const FileOptions<Traits>&) { return hpp::proto::string_literal<"type.googleapis.com/hpp.proto.FileOptions">{}; }
// NOLINTEND(performance-enum-size)
} // namespace hpp::proto
// clang-format on
