// clang-format off
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// generation command line:
//    protoc --plugin=protoc-gen-hpp=/path/to/protoc-gen-hpp
//           --hpp_out :${out_dir}
//           hpp_proto/hpp_options.proto

#pragma once

#include <hpp_proto/json.hpp>
#include "google/protobuf/descriptor.glz.hpp"
#include "hpp_proto/hpp_options.msg.hpp"

template <typename Traits>
struct glz::meta<hpp_proto::FileOptions<Traits>> {
  using T = hpp_proto::FileOptions<Traits>;
  static constexpr auto value = object(
    "namespacePrefix", &T::namespace_prefix);
};

template <typename Traits>
struct hpp_proto::has_glz<hpp_proto::FileOptions<Traits>> : std::true_type {};
// clang-format on
