// clang-format off
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// generation command line:
//    protoc --plugin=protoc-gen-hpp=/path/to/protoc-gen-hpp
//           --hpp_out :${out_dir}
//           hpp_proto/hpp_options.proto

#pragma once

#include <hpp_proto/binpb.hpp>
#include "hpp_proto/hpp_options.msg.hpp"
#include "google/protobuf/descriptor.pb.hpp"


namespace hpp_proto {

template <typename Traits>
auto pb_meta(const FileOptions<Traits> &) -> std::tuple<
  ::hpp_proto::field_meta<2, &FileOptions<Traits>::namespace_prefix, ::hpp_proto::field_option::explicit_presence>,
  ::hpp_proto::field_meta<UINT32_MAX, &FileOptions<Traits>::unknown_fields_>>;

template <typename Traits = ::hpp_proto::default_traits>
struct hpp_file_opts
    : ::hpp_proto::extension_base<hpp_file_opts<Traits>, google::protobuf::FileOptions> {
  using value_type=hpp_proto::FileOptions<Traits>;
  value_type value = {};
  using pb_meta = std::tuple<::hpp_proto::field_meta<8964, &hpp_file_opts<Traits>::value, ::hpp_proto::field_option::none, void, std::monostate{}>>;
};

} // namespace hpp_proto
// clang-format on
