// clang-format off
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// generation command line:
//    protoc --plugin=protoc-gen-hpp=/path/to/protoc-gen-hpp
//           --hpp_out proto2_explicit_presence=.google.protobuf.FieldDescriptorProto.oneof_index,proto2_explicit_presence=.google.protobuf.FieldOptions.packed:${out_dir}
//           google/protobuf/compiler/plugin.proto

#pragma once

#include <hpp_proto/binpb.hpp>
#include "google/protobuf/compiler/plugin.msg.hpp"
#include "google/protobuf/descriptor.pb.hpp"


namespace google::protobuf::compiler {

template <typename Traits>
auto pb_meta(const Version<Traits> &) -> std::tuple<
  ::hpp_proto::field_meta<1, &Version<Traits>::major, ::hpp_proto::field_option::none, ::hpp_proto::vint64_t>,
  ::hpp_proto::field_meta<2, &Version<Traits>::minor, ::hpp_proto::field_option::none, ::hpp_proto::vint64_t>,
  ::hpp_proto::field_meta<3, &Version<Traits>::patch, ::hpp_proto::field_option::none, ::hpp_proto::vint64_t>,
  ::hpp_proto::field_meta<4, &Version<Traits>::suffix, ::hpp_proto::field_option::none>,
  ::hpp_proto::field_meta<UINT32_MAX, &Version<Traits>::unknown_fields_>>;

template <typename Traits>
auto pb_meta(const CodeGeneratorRequest<Traits> &) -> std::tuple<
  ::hpp_proto::field_meta<1, &CodeGeneratorRequest<Traits>::file_to_generate, ::hpp_proto::field_option::none>,
  ::hpp_proto::field_meta<2, &CodeGeneratorRequest<Traits>::parameter, ::hpp_proto::field_option::none>,
  ::hpp_proto::field_meta<15, &CodeGeneratorRequest<Traits>::proto_file, ::hpp_proto::field_option::none>,
  ::hpp_proto::field_meta<17, &CodeGeneratorRequest<Traits>::source_file_descriptors, ::hpp_proto::field_option::none>,
  ::hpp_proto::field_meta<3, &CodeGeneratorRequest<Traits>::compiler_version, ::hpp_proto::field_option::explicit_presence>,
  ::hpp_proto::field_meta<UINT32_MAX, &CodeGeneratorRequest<Traits>::unknown_fields_>>;

template <typename Traits>
auto pb_meta(const CodeGeneratorResponse<Traits> &) -> std::tuple<
  ::hpp_proto::field_meta<1, &CodeGeneratorResponse<Traits>::error, ::hpp_proto::field_option::none>,
  ::hpp_proto::field_meta<2, &CodeGeneratorResponse<Traits>::supported_features, ::hpp_proto::field_option::none, ::hpp_proto::vuint64_t>,
  ::hpp_proto::field_meta<3, &CodeGeneratorResponse<Traits>::minimum_edition, ::hpp_proto::field_option::none, ::hpp_proto::vint64_t>,
  ::hpp_proto::field_meta<4, &CodeGeneratorResponse<Traits>::maximum_edition, ::hpp_proto::field_option::none, ::hpp_proto::vint64_t>,
  ::hpp_proto::field_meta<15, &CodeGeneratorResponse<Traits>::file, ::hpp_proto::field_option::none>,
  ::hpp_proto::field_meta<UINT32_MAX, &CodeGeneratorResponse<Traits>::unknown_fields_>>;

namespace CodeGeneratorResponse_ {
  template <typename Traits>
  auto pb_meta(const File<Traits> &) -> std::tuple<
    ::hpp_proto::field_meta<1, &File<Traits>::name, ::hpp_proto::field_option::none>,
    ::hpp_proto::field_meta<2, &File<Traits>::insertion_point, ::hpp_proto::field_option::none>,
    ::hpp_proto::field_meta<15, &File<Traits>::content, ::hpp_proto::field_option::none>,
    ::hpp_proto::field_meta<16, &File<Traits>::generated_code_info, ::hpp_proto::field_option::explicit_presence>,
    ::hpp_proto::field_meta<UINT32_MAX, &CodeGeneratorResponse_::File<Traits>::unknown_fields_>>;

} //namespace CodeGeneratorResponse_

} // namespace google::protobuf::compiler
// clang-format on
