// clang-format off
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// generation command line:
//    protoc --plugin=protoc-gen-hpp=/path/to/protoc-gen-hpp
//           --hpp_out proto2_explicit_presence=.google.protobuf.FieldDescriptorProto.oneof_index,proto2_explicit_presence=.google.protobuf.FieldOptions.packed:${out_dir}
//           google/protobuf/compiler/plugin.proto

#pragma once
#include <hpp_proto/file_descriptor_pb.hpp>

#include "google/protobuf/descriptor.desc.hpp"

namespace hpp_proto::file_descriptors::google::protobuf::compiler::plugin_proto {

using namespace std::literals::string_view_literals;
inline constexpr ::hpp_proto::file_descriptor_pb file_descriptor_{
  "\n%google/protobuf/compiler/plugin.proto\022\030google.protobuf.compiler\032 google/protobuf/descriptor.proto\"[\n\aVersion\022\022\n\005major\030\001(\005R\005major\022\022\n\005minor\030\002(\005R\005minor\022\022\n\005patch\030\003(\005R\005patch\022\024\n\006suffix\030\004(\tR\006suffix\"\313\002\n\024CodeGeneratorRequest\022(\n\020file_to_generate\030\001 \003(\tR\016fileToGenerate\022\032\n\tparameter\030\002(\tR\tparameter\022C\n\nproto_file\030\017 \003(\v2$.google.protobuf.FileDescriptorProtoR\tprotoFile\022\\\n\027source_file_descriptors\030\021 \003(\v2$.google.protobuf.FileDescriptorProtoR\025sourceFileDescriptors\022J\n\020compiler_version\030\003(\v2!.google.protobuf.compiler.VersionR\017compilerVersion\"\363\003\n\025CodeGeneratorResponse\022\022\n\005error\030\001(\tR\005error\022+\n\022supported_features\030\002(\004R\021supportedFeatures\022%\n\017minimum_edition\030\003(\005R\016minimumEdition\022%\n\017maximum_edition\030\004(\005R\016maximumEdition\022H\n\004file\030\017 \003(\v24.google.protobuf.compiler.CodeGeneratorResponse.FileR\004file\032\251\001\n\004File\022\020\n\004name\030\001(\tR\004name\022%\n\017insertion_point\030\002(\tR\016insertionPoint\022\026\n\acontent\030\017(\tR\acontent\022P\n\023generated_code_info\030\020(\v2\".google.protobuf.GeneratedCodeInfoR\021generatedCodeInfo\"U\n\aFeature\022\016\n\fFEATURE_NONE\022\033\n\027FEATURE_PROTO3_OPTIONAL\020\001\022\035\n\031FEATURE_SUPPORTS_EDITIONS\020\002Br\n\034com.google.protobuf.compilerB\fPluginProtosZ)google.golang.org/protobuf/types/pluginpb\252\002\030Google.Protobuf.Compiler"sv
};

inline auto file_descriptor_set(){
  return ::hpp_proto::distinct_file_descriptor_pb_array{
    ::hpp_proto::file_descriptors::google::protobuf::descriptor_proto::file_descriptor_,
    ::hpp_proto::file_descriptors::google::protobuf::compiler::plugin_proto::file_descriptor_,
  };
}
} // namespace hpp_proto::file_descriptors::google::protobuf::compiler::plugin_proto

// clang-format on
