name: ClusterFuzzLite continuous builds
on:
  workflow_dispatch:
  push:
    branches:
      - main  # Use your actual default branch here.
permissions:
  contents: read
  actions: read
jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [address, undefined]
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      with:
        persist-credentials: false
    - name: Setup C++ tools
      uses: aminya/setup-cpp@8170d66c458f4a045220b7b0966c10940bb2a15d # v1.8.1
      with:
        ccache: true
    - name: Build Fuzzers (${{ matrix.sanitizer }})
      id: build
      uses: ./.github/actions/cflite-build-fuzzers
      with:
        sanitizer: ${{ matrix.sanitizer }}
        upload-build: true
