---
  name: Linux
  
  on:
    workflow_dispatch:
    push:
      branches:
        - main
        - develop
        - dev/**
      paths-ignore:
        - '**.md'
    pull_request:
      branches:
        - main
        - develop
      paths-ignore:
        - '**.md'
  
  env:
    CTEST_OUTPUT_ON_FAILURE: 1
    CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules
    CCACHE_DIR: ${{ github.workspace }}/.ccache
  
  permissions:
    contents: read

  jobs:
    build:
      strategy:
        fail-fast: false
        matrix:
          include:
            - os: ubuntu-24.04
              compiler: gcc-14
              cmake_preset: ci-linux-release
              cpp_standard: 23
            - os: ubuntu-24.04
              compiler: llvm-20
              cmake_preset: ci-linux-release
              cpp_standard: 23
            - os: ubuntu-24.04
              compiler: llvm-22
              cmake_preset: ci-linux-release
              cpp_standard: 26
            - os: ubuntu-24.04
              compiler: llvm-20
              cmake_preset: ci-linux-asan-ubsan
              cpp_standard: 23
            - os: ubuntu-24.04
              compiler: gcc-13
              cmake_preset: ci-linux-coverage
              cpp_standard: 23

      runs-on: ${{ matrix.os }}
      defaults:
        run:
          shell: bash
      steps:
        - name: Install protoc
          run: |
            sudo apt-get update
            sudo apt-get install -y git protobuf-compiler

        - name: Install libgrpc++
          if: matrix.cmake_preset != 'ci-linux-asan-ubsan'
          run: |
            sudo apt-get install -y libprotobuf-dev libgrpc++-dev protobuf-compiler-grpc
        - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
          with:
            persist-credentials: false

        - name: Setup required C++ tools
          uses: aminya/setup-cpp@8170d66c458f4a045220b7b0966c10940bb2a15d # v1.8.1
          with:
            compiler: ${{ matrix.compiler }}
            cmake: "4.4.0"
            ninja: true
            ccache: true

        - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
          with:
            path: "**/cpm_modules"
            key: ${{ runner.os }}-${{ matrix.compiler }}-cxx${{ matrix.cpp_standard }}-${{ matrix.cmake_preset }}-cpm-modules-${{ hashFiles('**/third-parties.cmake') }}

        - name: Cache ccache
          uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
          with:
            path: ${{ env.CCACHE_DIR }}
            key: ${{ github.workflow }}-${{ runner.os }}-${{ matrix.compiler }}-cxx${{ matrix.cpp_standard }}-${{ matrix.cmake_preset }}-ccache-${{ github.sha }}
            restore-keys: |
              ${{ github.workflow }}-${{ runner.os }}-${{ matrix.compiler }}-cxx${{ matrix.cpp_standard }}-${{ matrix.cmake_preset }}-ccache-
  
        - name: install lcov
          if: matrix.cmake_preset == 'ci-linux-coverage'
          run: |
            sudo apt-get install -y lcov
            
        - name: configure
          run: cmake --preset "${{ matrix.cmake_preset }}" -DCMAKE_CXX_STANDARD=${{ matrix.cpp_standard }}
  
        - name: build
          run: cmake --build build -j"$(nproc)"
  
        - name: test
          working-directory: ./build
          run: |
            ctest --output-on-failure

        - name: capture coverage
          if: matrix.cmake_preset == 'ci-linux-coverage'
          run: |
            cmake --build build --target coverage_filtered_info

        - name: Upload coverage to Codecov
          uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
          if: matrix.cmake_preset == 'ci-linux-coverage'
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            files: build/coverage.filtered.info
            flags: linux
            name: linux-coverage
            verbose: true
