name: Workflow Lint

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
      - dev/**
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false

      - name: Run actionlint
        uses: docker://rhysd/actionlint@sha256:b1934ee5f1c509618f2508e6eb47ee0d3520686341fec936f3b79331f9315667 # 1.7.12
        with:
          args: -color
